[package]
name = "rende-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
liquid = "0.26.1"
resvg = "0.31.0"
tiny-skia = "0.8.3"
usvg = "0.31.0"